AWSTemplateFormatVersion: '2010-09-09'

Description: AWS API Gateway for Employees API

Resources:

  ApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: "employees-api"
      Name: employees-api
      Body:
        ### init API swagger (TODO: use external .yml file) ###
        swagger: '2.0'
        info:
          description: REST API to control employees
          title: Employees API
        schemes:
          - https
        paths:
          /employees:
            get:
              tags:
                - employees
              summary: List all employees
              produces:
                - application/json
              parameters:
                - name: department
                  in: query
                  description: The department of employee to retrieve
                  required: false
                  type: string
                - name: page
                  in: query
                  description: Page number of results to return.
                  required: false
                  type: string
              responses:
                '200':
                  description: Successful operation
                  schema:
                    $ref: '#/definitions/Employees'
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
                      description: URI that may access the resource
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: 200
                    responseTemplates:
                      application/json: '[{"id": 1, "name": "Wharley", "department":"technology"}, {"id": 2, "name": "Juan", "department":"technology"}, {"id": 3, "name": "Peter", "department":"sales"}]'
                requestParameters:
                  integration.request.querystring.page: method.request.querystring.page
                  integration.request.querystring.department: method.request.querystring.department
                passthroughBehavior: when_no_match
                requestTemplates:
                  application/json: '{"statusCode": 200}'
                type: mock
            post:
              tags:
                - employees
              operationId: CreateEmployee
              summary: Create an employee
              consumes:
                - application/json
              produces:
                - application/json
              parameters:
                - in: body
                  name: NewEmployee
                  required: true
                  schema:
                    $ref: '#/definitions/NewEmployee'
              responses:
                '200':
                  description: Successful operation
                  schema:
                    $ref: '#/definitions/NewEmployeeResponse'
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
                      description: URI that may access the resource
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: 200
                    responseParameters:
                      method.response.header.Access-Control-Allow-Origin: '''*'''
                passthroughBehavior: when_no_match
                httpMethod: POST
                requestTemplates:
                  application/json: '{"statusCode": 200}'
                type: mock
            put:
              tags:
                - employees
              operationId: UpdateEmployee
              summary: Updates an employee
              consumes:
                - application/json
              produces:
                - application/json
              parameters:
                - in: body
                  name: NewEmployee
                  required: true
                  schema:
                    $ref: '#/definitions/NewEmployee'
                - name: employeeId
                  in: path
                  description: The id of the pet to delete
                  required: true
                  type: string
              responses:
                '200':
                  description: Successful operation
                  schema:
                    $ref: '#/definitions/NewEmployeeResponse'
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
                      description: URI that may access the resource
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: 200
                    responseParameters:
                      method.response.header.Access-Control-Allow-Origin: '''*'''
                passthroughBehavior: when_no_match
                httpMethod: POST
                requestTemplates:
                  application/json: '{"statusCode": 200}'
                type: mock
            delete:
              tags:
                - employees
              summary: Delete a specific employee
              operationId: DeleteEmployee
              produces:
                - application/json
              parameters:
                - name: employeeId
                  in: path
                  description: The id of the employee to delete
                  required: true
                  type: string
              responses:
                '200':
                  description: Successful operation
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
                      description: URI that may access the resource
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: 200
                    responseParameters:
                      method.response.header.Access-Control-Allow-Origin: '''*'''
                requestParameters:
                  integration.request.path.employeeId: method.request.path.employeeId
                passthroughBehavior: when_no_match
                httpMethod: DELETE
                requestTemplates:
                  application/json: '{"statusCode": 200}'
                type: mock
        definitions:
          Employees:
            type: array
            items:
              $ref: '#/definitions/Employee'
          Empty:
            type: object
          NewEmployeeResponse:
            type: object
            properties:
              employee:
                $ref: '#/definitions/Employee'
          Employee:
            type: object
            properties:
              id:
                type: integer
              department:
                type: string
              name:
                type: string
          NewEmployee:
            type: object
            properties:
              department:
                $ref: '#/definitions/EmployeeDepartment'
              name:
                type: string
          EmployeeDepartment:
            type: string
            enum:
              - technology
              - sales
              - secretarial
              - marketing
              - security
        x-amazon-apigateway-documentation:
          version: v2.1
          createdDate: '2016-11-17T07:03:59Z'
          documentationParts:
            - location:
                type: API
              properties:
                info:
                  description: THe Employees API
            - location:
                type: METHOD
                method: GET
              properties:
                tags:
                  - employees
                description: Employees HTML web page containing API usage information
            - location:
                type: METHOD
                path: /emplpyees
                method: GET
              properties:
                tags:
                  - pets
                summary: List all employees
            - location:
                type: METHOD
                path: /employees
                method: POST
              properties:
                tags:
                  - pets
                summary: Create an employee
            - location:
                type: QUERY_PARAMETER
                path: /employees
                method: GET
                name: page
              properties:
                description: Page number of results to return.
            - location:
                type: QUERY_PARAMETER
                path: /employees
                method: GET
                name: department
              properties:
                description: The department of employees to retrieve
            - location:
                type: REQUEST_BODY
                path: /employees
                method: POST
              properties:
                description: Employee object that needs to be created
            - location:
                type: RESPONSE
                method: '*'
                statusCode: 200
              properties:
                description: Successful operation
            - location:
                type: RESPONSE_HEADER
                method: OPTIONS
                statusCode: 200
                name: Access-Control-Allow-Headers
              properties:
                description: Used in response to a preflight request to indicate which HTTP headers can be used when making the request.
            - location:
                type: RESPONSE_HEADER
                method: OPTIONS
                statusCode: 200
                name: Access-Control-Allow-Methods
              properties:
                description: Method or methods allowed when accessing the resource
            - location:
                type: RESPONSE_HEADER
                method: '*'
                statusCode: 200
                name: Access-Control-Allow-Origin
              properties:
                description: URI that may access the resource
            - location:
                type: RESPONSE_HEADER
                method: GET
                statusCode: 200
                name: Content-Type
              properties:
                description: Media type of request
        ### end API swagger ###
      FailOnWarnings: true
