AWSTemplateFormatVersion: '2010-09-09'

Description: AWS API Gateway for Employees API

Resources:
  DynamoDB:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: department
          AttributeType: S
        - AttributeName: id
          AttributeType: N
      BillingMode: PAY_PER_REQUEST
      KeySchema: 
        - AttributeName: department
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      TableName: employee
      GlobalSecondaryIndexes: 
        - IndexName: gsi_pk
          KeySchema: 
            - AttributeName: department
              KeyType: HASH
            - AttributeName: id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL